---
name: Merge

on:
  push:
    branches:
      - main

jobs:
  deploy_flatpak:
    name: Deploy Flatpak (${{ matrix.configuration.arch }})
    runs-on: ${{ matrix.configuration.runs-on }}

    strategy:
      matrix:
        configuration:
          - arch: x86_64
            runs-on: ubuntu-latest
          - arch: aarch64
            runs-on: ubuntu-24.04-arm
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false

    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:8-${{ matrix.configuration.arch }}
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust SDK extension
        run: |
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y --arch=${{ matrix.configuration.arch }} org.freedesktop.Sdk.Extension.rust-stable//23.08

      - name: Build
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6.5
        with:
          bundle: camera.flatpak
          manifest-path: io.elementary.camera.yml
          run-tests: true
          repository-name: appcenter
          repository-url: https://flatpak.elementary.io/repo.flatpakrepo
          cache-key: "flatpak-builder-${{ github.sha }}"
          branch: daily
          arch: ${{ matrix.configuration.arch }}

      - name: Deploy
        uses: flatpak/flatpak-github-actions/flat-manager@v6.5
        with:
          repository: appcenter
          flat-manager-url: https://flatpak-api.elementary.io
          token: ${{ secrets.FLAT_MANAGER_TOKEN }}

  gettext:
    name: Gettext
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:8-x86_64
      options: --privileged

    steps:
    - name: Install git, python3-git and jq
      run: |
        apt-get update
        apt-get install git jq python3-git -y

    - name: Clone repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GIT_USER_TOKEN }}

    - name: Install Rust SDK extension
      run: |
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak install -y org.freedesktop.Sdk.Extension.rust-stable//23.08

    - name: Configure Git
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Update Translation Files
      uses: elementary/actions/gettext-flatpak@main
      with:
        manifest-path: 'io.elementary.camera.yml'
      env:
        GIT_USER_NAME: "elementaryBot"
        GIT_USER_EMAIL: "builds@elementary.io"
